### ISSUE TITLE
Modal widget

### ISSUE THREAD

**Issue by shkolin** [yiisoft/yii-bulma#21]
- [x] Modal::class
- [x] ModalCard::class
- [ ] ~~ModalPluginAsset::class~~

This [modal component](https://bulma.io/documentation/components/modal/) has two visual interfaces, does it make sense to divide it into two classes? I think yes. What do you think?

**Comment by samdark** [comment]
By the looks of it, yes. It makes sense,

**Comment by shkolin** [comment]
@samdark https://github.com/yiisoft/yii-bulma/pull/20#discussion_r531239012
