### ISSUE TITLE
Field widget does not default to Bulma styles

### ISSUE THREAD

**Issue by igbanam** [yiisoft/yii-bulma#43]
I have the `yii-bulma` package setup with `yii-form`. The default form fields still default to the Bootstrap version, even after there seems to be a mod to the `Field::class` to use the spec in `$params['yiisoft/form']['bulma']['fieldConfig']`.

How do I get this wired up properly to use Bulma as the default?

### What steps will reproduce the problem?
- Start a new Yii 3 project with the `yiisoft/app` template — this comes with `yii/bulma`
- `composer require yiisoft/form`
- Create a new form with a form field from `Yiisoft\Form\Widget\Field`
  - i.e. `<?= Field::widget()->config($form, 'title') ?>`

### What is the expected result?
The label on the field should be defined as 
```
<label>Title</label>
```
…where Bulma takes care of the styling

### What do you get instead?
```
<label class="control-label">Title</label>
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      | 8
| Operating system | OS X

**Comment by samdark** [comment]
@terabytesoftw would you please take a look?

**Comment by terabytesoftw** [comment]
@igbanam You can attach your composer.json.

**Comment by igbanam** [comment]
https://gist.github.com/igbanam/472da62c8a61ff5b8358bf6feb68f755

**Comment by terabytesoftw** [comment]
https://bulma.io/documentation/form/general/#complete-form-example, fixed default bulma config.
